REPORTER_PATH=C:\ReportTools\current\reporter\
DATABASE_PATH=D:\measures_database\
INPUT_FILES_PATH=C:\ReportTools\current\input_files\
PROCESSED_FILES_PATH=D:\HEXAGON\Programas\(not id) - Full Frame\03-REPORTES\
BACKUPS_PATH=C:\ReportTools\current\database_backups\